const KEY="nova-forest-my-areas-v1";
const areasEl=document.getElementById("areas"),emptyEl=document.getElementById("empty"),countEl=document.getElementById("count");
function getAreas(){return JSON.parse(localStorage.getItem(KEY)||"[]")}
function center(points){let lat=0,lon=0;points.forEach(p=>{lat+=p[0];lon+=p[1]});return[lat/points.length,lon/points.length]}
function scoreRisk(w){let s=0;if(w.t>=40)s+=30;else if(w.t>=30)s+=15;else if(w.t>=25)s+=7;if(w.h<=20)s+=25;else if(w.h<=40)s+=10;else if(w.h<=55)s+=4;if(w.wind>=40)s+=25;else if(w.wind>=20)s+=10;else if(w.wind>=12)s+=4;if(w.soil<.18)s+=10;return Math.min(100,s)}
function crop(w){return Math.max(0,Math.min(100,100-(w.soil<.15?65:w.soil<.2?40:w.soil<.27?15:0)-(w.et0>5?20:w.et0>3?8:0)-(w.vpd>2?12:w.vpd>1.5?5:0)))}
function bee(w,pollen){let s=100;if(w.t<14||w.t>34)s-=30;if(w.wind>25)s-=35;else if(w.wind>15)s-=15;if(w.precip>1)s-=35;if(pollen>120)s-=5;return Math.max(0,Math.min(100,s))}
async function live(lat,lon){const u=new URL("https://api.open-meteo.com/v1/forecast");u.searchParams.set("latitude",lat);u.searchParams.set("longitude",lon);u.searchParams.set("current","temperature_2m,relative_humidity_2m,wind_speed_10m,precipitation,soil_moisture_0_to_7cm,vapour_pressure_deficit");u.searchParams.set("daily","et0_fao_evapotranspiration,precipitation_sum");u.searchParams.set("forecast_days","3");u.searchParams.set("timezone","Europe/Istanbul");const j=await fetch(u).then(r=>r.json());const c=j.current||{},d=j.daily||{};const w={t:Number(c.temperature_2m||0),h:Number(c.relative_humidity_2m||0),wind:Number(c.wind_speed_10m||0),precip:Number(c.precipitation||0),soil:Number(c.soil_moisture_0_to_7cm||0),vpd:Number(c.vapour_pressure_deficit||0),et0:Number(d.et0_fao_evapotranspiration?.[0]||0)};let pollen=0;try{const p=new URL("https://air-quality-api.open-meteo.com/v1/air-quality");p.searchParams.set("latitude",lat);p.searchParams.set("longitude",lon);p.searchParams.set("current","alder_pollen,birch_pollen,grass_pollen,mugwort_pollen,olive_pollen,ragweed_pollen");p.searchParams.set("timezone","Europe/Istanbul");const q=(await fetch(p).then(r=>r.json())).current||{};pollen=Math.max(...["alder_pollen","birch_pollen","grass_pollen","mugwort_pollen","olive_pollen","ragweed_pollen"].map(k=>Number(q[k]||0)))}catch{}return{w,pollen,risk:scoreRisk(w),crop:crop(w),bee:bee(w,pollen)}}
async function satellite(a){try{const base=(window.NOVA_API_BASE||"").replace(/\/$/,"");if(!base)return{status:"backend_bekleniyor",series:[]};const ring=a.coordinates.map(p=>[p[1],p[0]]);ring.push(ring[0]);const r=await fetch(base+"/ndvi/area-timeseries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({geometry:{type:"Polygon",coordinates:[ring]},days:180,interval:"P30D"})});return await r.json()}catch{return{status:"error",series:[]}}}
function alerts(a,d){const out=[];if(d.w.soil<.15)out.push(["SU STRESİ","Toprak nemi çok düşük. Sulama kontrolü gerekli.","warn"]);else if(d.w.soil<.20)out.push(["NEM DÜŞÜYOR","Toprak nemi izleme eşiğinin altında.","info"]);if(d.w.vpd>2)out.push(["ATMOSFERİK STRES","VPD yüksek; bitkinin su kaybı baskısı artıyor.","warn"]);if(d.w.wind>25)out.push(["RÜZGAR","Rüzgar yüksek; arıcılık uçuş koşulu zayıflayabilir.","warn"]);if(d.w.precip>5)out.push(["YAĞIŞ","Yağış yüksek; tarla operasyonunu kontrol et.","info"]);if(a.type.includes("arı")&&d.bee<50)out.push(["ARICILIK UYARISI","Uçuş koşulu şu anda elverişli görünmüyor.","warn"]);if(a.type.includes("çift")&&d.crop<45)out.push(["TARIM UYARISI","Koşullar bitki stresi yönünde; uyduyla teyit edilmeli.","warn"]);if(!out.length)out.push(["SİSTEM NORMAL","Belirgin otomatik olay eşiği aşılmadı.","ok"]);return out}
function satelliteBox(sat){if(sat.status==="available"&&sat.series?.length){const last=sat.series[sat.series.length-1],prev=sat.series.length>1?sat.series[sat.series.length-2]:null;const delta=prev?(last.ndvi-prev.ndvi):null;return '<div class="sat-mini"><div><span>UYDU ZAMAN SERİSİ</span><b>'+last.ndvi.toFixed(2)+' NDVI</b></div><small>'+last.classification+(delta===null?"":" · "+(delta>=0?"+":"")+delta.toFixed(2)+" değişim")+'</small></div>'}if(sat.status==="not_configured")return '<div class="sat-mini muted"><span>UYDU</span><b>CDSE bağlantısı bekleniyor</b><small>Backend’e Sentinel Hub OAuth bilgileri tanımlanınca gerçek NDVI zaman serisi çalışır.</small></div>';return '<div class="sat-mini muted"><span>UYDU</span><b>Sahne/işleme bekleniyor</b><small>Alan bazlı Sentinel-2 istatistiği hazırlanıyor.</small></div>'}
async function card(a){const [lat,lon]=center(a.coordinates);const [d,sat]=await Promise.all([live(lat,lon),satellite(a)]);const alertsHtml=alerts(a,d).map(x=>'<div class="area-alert '+x[2]+'"><b>'+x[0]+'</b><span>'+x[1]+'</span></div>').join("");return '<article class="area-card"><div class="area-card-head"><div><div class="eyebrow">'+a.type.toUpperCase()+'</div><h3>'+a.name+'</h3><p>'+a.province+(a.district?" · "+a.district:"")+'</p></div><button data-delete="'+a.id+'">Sil</button></div><div class="area-live"><span>CANLI DURUM</span><strong>'+d.risk+'/100 risk</strong><small>Güncelleme: '+new Date().toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"})+'</small></div><div class="area-metrics"><div><span>Sıcaklık</span><b>'+d.w.t+' °C</b></div><div><span>Toprak nemi</span><b>'+Math.round(d.w.soil*100)+' %</b></div><div><span>ET₀</span><b>'+d.w.et0.toFixed(1)+' mm</b></div><div><span>VPD</span><b>'+d.w.vpd.toFixed(2)+'</b></div><div><span>Tarım skoru</span><b>'+d.crop+'/100</b></div><div><span>Arı uçuş</span><b>'+d.bee+'/100</b></div></div>'+satelliteBox(sat)+'<div class="area-alerts"><h4>Otomatik olaylar</h4>'+alertsHtml+'</div><div class="area-footer">Koordinat merkezi: '+lat.toFixed(4)+', '+lon.toFixed(4)+' · Hava/toprak modeli canlıdır. Uydu zaman serisi Sentinel-2 sahneleri geldikçe güncellenir.</div></article>'}
async function render(){const areas=getAreas();countEl.textContent=areas.length+" alan";if(!areas.length){areasEl.innerHTML="";emptyEl.style.display="grid";return}emptyEl.style.display="none";areasEl.innerHTML='<div class="loading-area">Alanların canlı durumu hesaplanıyor…</div>';const html=await Promise.all(areas.map(card));areasEl.innerHTML=html.join("");areasEl.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>{localStorage.setItem(KEY,JSON.stringify(getAreas().filter(a=>a.id!==b.dataset.delete)));render()})}
render();setInterval(render,300000);
