(() => {
  const API = (window.NOVA_API_BASE || "http://localhost:8000").replace(/\/$/, "");
  const regions = {"Edirne":[41.6771,26.5557],"Tekirdağ":[40.9781,27.5110],"Kırklareli":[41.7355,27.2252],"Çanakkale":[40.1553,26.4142],"İstanbul":[41.1500,28.6500]};
  const root=document.querySelector("[data-forecast-center]"); if(!root)return;
  const esc=s=>String(s).replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
  const level=r=>r>=75?"KRİTİK":r>=50?"YÜKSEK":r>=25?"ORTA":"DÜŞÜK";
  const dayName=d=>new Date(d+"T12:00:00").toLocaleDateString("tr-TR",{weekday:"short",day:"2-digit",month:"short"});
  root.innerHTML=`<div class="forecast-toolbar"><div><span class="eyebrow">NEXORAWILDFIRE / PREDICTIVE ENGINE</span><h2>Önümüzdeki 7 Gün</h2><p>3 günlük kısa vadeli ve 1 haftalık genişletilmiş risk görünümü.</p></div><label>Analiz alanı<select data-region>${Object.keys(regions).map(x=>`<option>${x}</option>`).join("")}</select></label></div><div class="horizon-tabs"><button class="active" data-horizon="3">3 Gün</button><button data-horizon="7">1 Hafta</button></div><div class="forecast-grid" data-forecast-grid><div class="loading-state">Tahmin verileri hazırlanıyor…</div></div><div class="history-head"><div><span class="eyebrow">15 YILLIK GERİYE DÖNÜK ANALİZ</span><h2>Geçmiş Risk Eğilimi</h2></div><span class="data-badge">Son 15 yıl · Meteorolojik seri</span></div><div class="history-chart" data-history-chart><div class="loading-state">15 yıllık veri yükleniyor…</div></div><p class="forecast-note">Model, meteorolojik geçmiş ve tahmin verilerinden NexoraWildfire risk skorunu hesaplar. Bu çıktı kesin yangın tahmini değildir; erken uyarı ve karar destek sinyalidir.</p>`;
  const grid=root.querySelector("[data-forecast-grid]"),chart=root.querySelector("[data-history-chart]"),select=root.querySelector("[data-region]"); let horizon=3,cache={};
  async function load(name){const [lat,lon]=regions[name];grid.innerHTML=`<div class="loading-state">${esc(name)} için tahmin alınıyor…</div>`;chart.innerHTML=`<div class="loading-state">Geçmiş seri alınıyor…</div>`;try{const [fRes,hRes]=await Promise.all([fetch(`${API}/forecast-risk?lat=${lat}&lon=${lon}`),fetch(`${API}/historical-risk?lat=${lat}&lon=${lon}&years=15`)]);if(!fRes.ok||!hRes.ok)throw new Error("API yanıtı alınamadı");const data={forecast:await fRes.json(),history:await hRes.json()};cache[name]=data;renderForecast(data.forecast.days||[]);renderHistory(data.history.years||[])}catch(e){grid.innerHTML=`<div class="error-state">Tahmin servisine ulaşılamadı. Backend bağlantısını kontrol edin.</div>`;chart.innerHTML=`<div class="error-state">Geçmiş veri servisine ulaşılamadı.</div>`}}
  function renderForecast(days){grid.innerHTML=days.slice(0,horizon).map((d,i)=>`<article class="forecast-card"><div class="forecast-date">${i===0?"BUGÜN":dayName(d.date)}</div><div class="forecast-risk">${Math.round(d.risk)}<small>/100</small></div><strong>${level(d.risk)}</strong><div class="forecast-metrics"><span>🌡 ${d.temperature_max.toFixed(1)}° / ${d.temperature_min.toFixed(1)}°</span><span>💧 ${d.humidity_min}%</span><span>🌬 ${d.wind_max.toFixed(1)} km/s</span><span>🌧 ${d.precipitation.toFixed(1)} mm</span></div></article>`).join("")}
  function renderHistory(years){if(!years.length){chart.innerHTML=`<div class="error-state">Geçmiş seri bulunamadı.</div>`;return}const max=Math.max(...years.map(x=>x.risk_average),1);chart.innerHTML=years.map(x=>`<div class="history-row"><span>${x.year}</span><div class="history-track"><i style="width:${Math.max(3,x.risk_average/max*100)}%"></i></div><b>${x.risk_average}</b><small>maks ${x.risk_max}</small></div>`).join("")}
  root.querySelectorAll("[data-horizon]").forEach(btn=>btn.addEventListener("click",()=>{horizon=Number(btn.dataset.horizon);root.querySelectorAll("[data-horizon]").forEach(x=>x.classList.toggle("active",x===btn));const d=cache[select.value];if(d)renderForecast(d.forecast.days||[])}));
  select.addEventListener("change",()=>load(select.value)); load(select.value);
})();
