(()=>{
const regions={Edirne:[41.6771,26.5557],Tekirdag:[40.9781,27.5110],Kirklareli:[41.7355,27.2252],Canakkale:[40.1553,26.4142],Istanbul:[41.1500,28.6500]};
const labels={Edirne:'Edirne',Tekirdag:'Tekirdağ',Kirklareli:'Kırklareli',Canakkale:'Çanakkale',Istanbul:'İstanbul'};
const root=document.querySelector('[data-forecast-center]');if(!root)return;
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const level=r=>r>=75?'KRİTİK':r>=50?'YÜKSEK':r>=25?'ORTA':'DÜŞÜK';
const dayName=d=>new Date(d+'T12:00:00').toLocaleDateString('tr-TR',{weekday:'short',day:'2-digit',month:'short'});
root.innerHTML=`<div class="forecast-toolbar"><div><span class="eyebrow">NEXORAWILDFIRE / PREDICTIVE ENGINE</span><h2>Önümüzdeki 7 Gün</h2><p>Canlı Open-Meteo tahmini; 3 günlük ve 1 haftalık görünüm.</p></div><label>Analiz alanı<select data-region>${Object.keys(regions).map(k=>`<option value="${k}">${labels[k]}</option>`).join('')}</select></label></div><div class="horizon-tabs"><button class="active" data-horizon="3">3 Gün</button><button data-horizon="7">1 Hafta</button></div><div class="forecast-grid" data-forecast-grid></div><div class="history-head"><div><span class="eyebrow">15 YILLIK GERİYE DÖNÜK ANALİZ</span><h2>Geçmiş Risk Eğilimi</h2></div><span class="data-badge">Gerçek meteorolojik arşiv</span></div><div class="history-chart" data-history-chart></div><p class="forecast-note">Risk skoru meteorolojik göstergelerden hesaplanan erken uyarı sinyalidir; kesin yangın tahmini değildir.</p>`;
const grid=root.querySelector('[data-forecast-grid]'),chart=root.querySelector('[data-history-chart]'),select=root.querySelector('[data-region]');let horizon=3,cache={};
function score(t,h,w){let s=0;if(t>=40)s+=30;else if(t>=30)s+=15;else if(t>=25)s+=7;if(h<=20)s+=25;else if(h<=40)s+=10;else if(h<=55)s+=4;if(w>=40)s+=25;else if(w>=20)s+=10;else if(w>=12)s+=4;return Math.min(100,s)}
async function load(name){const [lat,lon]=regions[name];grid.innerHTML=`<div class="loading-state">${labels[name]} için canlı tahmin alınıyor…</div>`;chart.innerHTML='<div class="loading-state">15 yıllık meteorolojik seri hesaplanıyor…</div>';try{const u=new URL('https://api.open-meteo.com/v1/forecast');u.searchParams.set('latitude',lat);u.searchParams.set('longitude',lon);u.searchParams.set('daily','temperature_2m_max,temperature_2m_min,relative_humidity_2m_min,wind_speed_10m_max,precipitation_sum');u.searchParams.set('forecast_days','7');u.searchParams.set('timezone','Europe/Istanbul');const f=await fetch(u).then(r=>r.json());const d=f.daily||{};const days=(d.time||[]).map((date,i)=>({date,temperature_max:Number(d.temperature_2m_max?.[i]??0),temperature_min:Number(d.temperature_2m_min?.[i]??0),humidity_min:Number(d.relative_humidity_2m_min?.[i]??0),wind_max:Number(d.wind_speed_10m_max?.[i]??0),precipitation:Number(d.precipitation_sum?.[i]??0),risk:score(Number(d.temperature_2m_max?.[i]??0),Number(d.relative_humidity_2m_min?.[i]??0),Number(d.wind_speed_10m_max?.[i]??0))}));cache[name]={days};renderForecast(days);const end=new Date();end.setDate(end.getDate()-1);const start=new Date(end);start.setFullYear(start.getFullYear()-15);const hu=new URL('https://archive-api.open-meteo.com/v1/archive');hu.searchParams.set('latitude',lat);hu.searchParams.set('longitude',lon);hu.searchParams.set('start_date',start.toISOString().slice(0,10));hu.searchParams.set('end_date',end.toISOString().slice(0,10));hu.searchParams.set('daily','temperature_2m_max,relative_humidity_2m_min,wind_speed_10m_max,precipitation_sum');hu.searchParams.set('timezone','Europe/Istanbul');const h=await fetch(hu).then(r=>r.json());const hd=h.daily||{};const byYear={};(hd.time||[]).forEach((date,i)=>{const y=date.slice(0,4);const t=Number(hd.temperature_2m_max?.[i]??0),rh=Number(hd.relative_humidity_2m_min?.[i]??0),w=Number(hd.wind_speed_10m_max?.[i]??0),p=Number(hd.precipitation_sum?.[i]??0),r=score(t,rh,w);(byYear[y]??=[]).push({r,t,rh,w,p})});const years=Object.entries(byYear).map(([year,a])=>({year,risk_average:Math.round(a.reduce((s,x)=>s+x.r,0)/a.length),risk_max:Math.max(...a.map(x=>x.r)),days:a.length}));renderHistory(years)}catch(e){grid.innerHTML='<div class="error-state">Canlı tahmin alınamadı. İnternet bağlantısını kontrol edin.</div>';chart.innerHTML='<div class="error-state">15 yıllık veri alınamadı.</div>';console.error(e)}}
function renderForecast(days){grid.innerHTML=days.slice(0,horizon).map((d,i)=>`<article class="forecast-card"><div class="forecast-date">${i===0?'BUGÜN':dayName(d.date)}</div><div class="forecast-risk">${d.risk}<small>/100</small></div><strong>${level(d.risk)}</strong><div class="forecast-metrics"><span>🌡 ${d.temperature_max.toFixed(1)}° / ${d.temperature_min.toFixed(1)}°</span><span>💧 ${d.humidity_min}%</span><span>🌬 ${d.wind_max.toFixed(1)} km/s</span><span>🌧 ${d.precipitation.toFixed(1)} mm</span></div></article>`).join('')}
function renderHistory(years){if(!years.length){chart.innerHTML='<div class="error-state">Geçmiş seri bulunamadı.</div>';return}const max=Math.max(...years.map(x=>x.risk_average),1);chart.innerHTML=years.map(x=>`<div class="history-row"><span>${x.year}</span><div class="history-track"><i style="width:${Math.max(3,x.risk_average/max*100)}%"></i></div><b>${x.risk_average}</b><small>${x.days} gün</small></div>`).join('')}
root.querySelectorAll('[data-horizon]').forEach(btn=>btn.addEventListener('click',()=>{horizon=Number(btn.dataset.horizon);root.querySelectorAll('[data-horizon]').forEach(x=>x.classList.toggle('active',x===btn));if(cache[select.value])renderForecast(cache[select.value].days)}));select.addEventListener('change',()=>load(select.value));load(select.value);
})();
