/* NexoraWildfire direct messages. All access is enforced again by Supabase RLS. */
(function(){
 const $=s=>document.querySelector(s);
 const gate=$("#messages-gate"),app=$("#messages-app"),list=$("#conversation-list"),findResult=$("#find-result");
 let client=null,user=null,selectedId=null,selectedUser=null,channel=null,poll=null,oldestMessageAt=null,loadingOlder=false,hasOlder=true,bootedUserId=null;
 const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
 function status(q,t){const x=$(q);if(x)x.textContent=t}
 function niceTime(v){if(!v)return"";const d=new Date(v);return Number.isNaN(+d)?"":d.toLocaleString("tr-TR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"})}
 function handleValue(v){return String(v||"").trim().replace(/^@/,"").toLowerCase()}
 function empty(text){list.innerHTML='<p class="muted-note">'+esc(text)+'</p>'}
 async function ownDirectory(){const {data,error}=await client.from("nexora_dm_directory").select("user_id,handle,display_name").eq("user_id",user.id).maybeSingle();if(error)throw error;return data}
 async function saveHandle(e){e.preventDefault();const f=new FormData(e.currentTarget),handle=handleValue(f.get("handle")),displayName=String(f.get("displayName")||"").trim().slice(0,60);if(!/^[a-z0-9_]{3,24}$/.test(handle))return status("[data-handle-status]","3–24 karakter; sadece harf, sayı ve alt çizgi.");if(!displayName)return status("[data-handle-status]","Görünen ad gerekli.");status("[data-handle-status]","Kaydediliyor…");const {data,error}=await client.from("nexora_dm_directory").upsert({user_id:user.id,handle,display_name:displayName,updated_at:new Date().toISOString()},{onConflict:"user_id"}).select().single();if(error){status("[data-handle-status]",error.code==="23505"?"Bu kullanıcı adı alınmış. Başka bir ad dene.":error.message||"Kaydedilemedi.");return}$("#handle").value=data.handle;$("#display-name").value=data.display_name;status("[data-handle-status]","Saha kimliğin kaydedildi.");}
 async function searchHandle(e){e.preventDefault();const handle=handleValue(new FormData(e.currentTarget).get("handle"));if(!/^[a-z0-9_]{3,24}$/.test(handle))return status("[data-find-status]","Geçerli kullanıcı adını yaz.");status("[data-find-status]","Aranıyor…");findResult.replaceChildren();const {data,error}=await client.from("nexora_dm_directory").select("user_id,handle,display_name").eq("handle",handle).maybeSingle();if(error){status("[data-find-status]",error.message||"Arama başarısız.");return}if(!data){status("[data-find-status]","Bu kullanıcı adı bulunamadı.");return}if(data.user_id===user.id){status("[data-find-status]","Bu senin hesabın.");return}status("[data-find-status]","Kullanıcı bulundu.");const card=document.createElement("div");card.className="directory-result";const label=document.createElement("div");label.innerHTML='<b>'+esc(data.display_name)+'</b><small>@'+esc(data.handle)+'</small>';const button=document.createElement("button");button.textContent="Mesaj gönder →";button.onclick=()=>startConversation(data.handle);card.append(label,button);findResult.append(card)}
 async function startConversation(handle){status("[data-find-status]","Konuşma açılıyor…");const {data,error}=await client.rpc("nexora_start_dm",{recipient_handle:handle});if(error){status("[data-find-status]",error.message||"Konuşma açılamadı.");return}await loadInbox();await openConversation(data,handle)}
 async function loadInbox(){if(!user)return;const {data,error}=await client.from("nexora_dm_participants").select("conversation_id,last_read_at,joined_at").eq("user_id",user.id).order("joined_at",{ascending:false}).limit(50);if(error){empty("Gelen kutusu yüklenemedi: "+(error.message||"veritabanı erişimini kontrol et"));return}if(!data?.length){empty("Henüz konuşma yok. Kullanıcı adıyla bir saha kullanıcısı bul.");return}const rows=await Promise.all(data.map(async p=>{const [pr,mr]=await Promise.all([client.from("nexora_dm_participants").select("user_id").eq("conversation_id",p.conversation_id),client.from("nexora_dm_messages").select("body,sender_id,created_at").eq("conversation_id",p.conversation_id).order("created_at",{ascending:false}).limit(1)]);const others=(pr.data||[]).map(x=>x.user_id).filter(id=>id!==user.id);let person=null;if(others.length){const d=await client.from("nexora_dm_directory").select("user_id,handle,display_name").in("user_id",others).limit(1);person=d.data?.[0]||null}return{id:p.conversation_id,person,last:mr.data?.[0]||null}}));rows.sort((a,b)=>new Date(b.last?.created_at||0)-new Date(a.last?.created_at||0));list.replaceChildren();rows.forEach(row=>{const b=document.createElement("button");b.type="button";b.className="conversation-item"+(row.id===selectedId?" active":"");const title=row.person?.display_name||"Saha kullanıcısı";const handle=row.person?.handle?"@"+row.person.handle:"Özel konuşma";const snippet=row.last?row.last.body:"Konuşma hazır · ilk mesajını gönder";b.innerHTML='<span class="conversation-avatar">'+esc(title.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase())+'</span><span class="conversation-copy"><b>'+esc(title)+'</b><small>'+esc(handle)+'</small><span>'+esc(snippet)+'</span></span><time>'+esc(niceTime(row.last?.created_at))+'</time>';b.onclick=()=>openConversation(row.id,row.person?.handle||"");list.append(b)})}
 async function openConversation(id,handle){selectedId=id;selectedUser=handle;oldestMessageAt=null;hasOlder=true;loadingOlder=false;$("#chat-placeholder").hidden=true;$("#chat-view").hidden=false;$("#chat-title").textContent=handle?"@"+handle:"Özel konuşma";$("#chat-handle").textContent="Yalnızca konuşma katılımcıları erişebilir";document.querySelectorAll(".conversation-item").forEach(x=>x.classList.remove("active"));await loadMessages(true);await loadInbox();if(channel){try{await client.removeChannel(channel)}catch{}}channel=client.channel("nexora-dm-"+id).on("postgres_changes",{event:"INSERT",schema:"public",table:"nexora_dm_messages",filter:"conversation_id=eq."+id},()=>loadMessages(true)).subscribe();if(poll)clearInterval(poll);poll=setInterval(()=>{if(selectedId)loadMessages(true)},15000)}
 async function loadMessages(reset=false){
  if(!selectedId||loadingOlder)return;
  const box=$("#chat-messages"),priorHeight=box.scrollHeight,priorTop=box.scrollTop;
  if(!reset&&oldestMessageAt&&!hasOlder)return;
  if(!reset)loadingOlder=true;
  let query=client.from("nexora_dm_messages").select("id,sender_id,body,created_at").eq("conversation_id",selectedId).order("created_at",{ascending:false}).limit(20);
  if(!reset&&oldestMessageAt)query=query.lt("created_at",oldestMessageAt);
  const {data,error}=await query;
  if(error){loadingOlder=false;status("[data-send-status]",error.message||"Mesajlar yüklenemedi.");return}
  const page=(data||[]).reverse();
  if(reset){box.replaceChildren();oldestMessageAt=page[0]?.created_at||null;hasOlder=(data||[]).length===20}
  else if(page.length){oldestMessageAt=page[0].created_at;hasOlder=page.length===20}else hasOlder=false;
  const frag=document.createDocumentFragment();
  page.forEach(m=>{const row=document.createElement("article");row.className="message-bubble"+(m.sender_id===user.id?" own":"");row.dataset.messageId=m.id;const body=document.createElement("p");body.textContent=m.body;const meta=document.createElement("time");meta.textContent=(m.sender_id===user.id?"Sen · ":"")+niceTime(m.created_at);row.append(body,meta);frag.append(row)});
  if(reset){box.replaceChildren();if(!page.length){const p=document.createElement("p");p.className="muted-note chat-first-note";p.textContent="Konuşma açıldı. İlk mesajı sen gönderebilirsin.";box.append(p)}box.append(frag);box.scrollTop=box.scrollHeight}
  else if(page.length){box.prepend(frag);box.scrollTop=box.scrollHeight-priorHeight+priorTop}
  loadingOlder=false;
 }
 async function loadOlderMessages(){if(!hasOlder||loadingOlder||!oldestMessageAt)return;await loadMessages(false)}
 async function sendMessage(e){e.preventDefault();if(!selectedId)return;const field=e.currentTarget.elements.body,body=field.value.trim();if(!body)return;if(body.length>4000)return status("[data-send-status]","Mesaj 4000 karakteri aşamaz.");const button=e.currentTarget.querySelector("button");button.disabled=true;status("[data-send-status]","Gönderiliyor…");const {error}=await client.from("nexora_dm_messages").insert({conversation_id:selectedId,sender_id:user.id,body});button.disabled=false;if(error){status("[data-send-status]",error.message||"Mesaj gönderilemedi.");return}field.value="";status("[data-send-status]","Gönderildi.");await loadMessages(true);await loadInbox()}
 async function boot(session){if(!session){bootedUserId=null;if(poll)clearInterval(poll);poll=null;if(channel){client?.removeChannel(channel).catch(()=>{});channel=null}client=null;user=null;selectedId=null;gate.hidden=false;app.hidden=true;return}if(bootedUserId===session.user.id&&client)return;bootedUserId=session.user.id;client=window.NovaAuth?.client();user=session.user;if(!client){gate.hidden=false;return}gate.hidden=true;app.hidden=false;$("#handle-form").addEventListener("submit",saveHandle);$("#find-form").addEventListener("submit",searchHandle);$("#send-form").addEventListener("submit",sendMessage);$("#refresh-inbox").onclick=loadInbox;$("#chat-refresh").onclick=()=>loadMessages(true);$("#chat-messages").addEventListener("scroll",()=>{if($("#chat-messages").scrollTop<50)loadOlderMessages()});try{const d=await ownDirectory();if(d){$("#handle").value=d.handle;$("#display-name").value=d.display_name}}catch(e){status("[data-handle-status]",e.message||"Profil yüklenemedi.")}await loadInbox()}
 document.addEventListener("nova:auth-ready",e=>boot(e.detail.session));setTimeout(()=>{if(!window.NovaAuth?.session())boot(null)},1300);
})();
