"""Train the optional research model from a real, documented historical CSV.

Expected columns: date, temperature_max, humidity_min, wind_max,
precipitation_sum, et0, vpd_max, precipitation_previous_6d,
firms_hotspot_proxy (0/1). The target is a satellite hotspot proxy, NOT a
verified fire incident. No synthetic data is generated by this script.
"""
from __future__ import annotations

import argparse
import json
import os
from datetime import datetime, timezone
from pathlib import Path

import joblib
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score, precision_score, recall_score, roc_auc_score
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

ROOT = Path(__file__).resolve().parents[1]
FEATURES = [
    "temperature_max", "humidity_min", "wind_max", "precipitation_sum",
    "et0", "vpd_max", "precipitation_previous_6d",
]
TARGET = "firms_hotspot_proxy"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--csv", required=True, help="Path to a licensed, documented historical observations CSV")
    parser.add_argument("--model-out", default=str(ROOT / "models" / "fire_risk.joblib"))
    parser.add_argument("--metadata-out", default=str(ROOT / "models" / "fire_risk_metadata.json"))
    parser.add_argument("--test-fraction", type=float, default=0.2)
    args = parser.parse_args()
    if not 0.1 <= args.test_fraction <= 0.4:
        parser.error("--test-fraction must be between 0.1 and 0.4")

    source = Path(args.csv)
    frame = pd.read_csv(source)
    required = ["date", *FEATURES, TARGET]
    missing = [column for column in required if column not in frame.columns]
    if missing:
        parser.error("Missing required CSV columns: " + ", ".join(missing))
    frame["date"] = pd.to_datetime(frame["date"], errors="coerce", utc=True)
    frame = frame.dropna(subset=["date", TARGET]).sort_values("date").reset_index(drop=True)
    frame[TARGET] = pd.to_numeric(frame[TARGET], errors="coerce")
    frame = frame[frame[TARGET].isin([0, 1])]
    if len(frame) < 100 or frame[TARGET].nunique() != 2:
        parser.error("Need at least 100 valid chronological rows containing both target classes; no model was written.")
    for feature in FEATURES:
        frame[feature] = pd.to_numeric(frame[feature], errors="coerce")
    frame = frame.dropna(subset=FEATURES, how="all")
    split = int(len(frame) * (1.0 - args.test_fraction))
    train, test = frame.iloc[:split], frame.iloc[split:]
    if train[TARGET].nunique() != 2 or test[TARGET].nunique() != 2:
        parser.error("Chronological train and test periods must each contain both classes; collect more representative data.")

    model = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("classifier", RandomForestClassifier(
            n_estimators=400, min_samples_leaf=3, class_weight="balanced",
            random_state=42, n_jobs=-1,
        )),
    ])
    model.fit(train[FEATURES], train[TARGET].astype(int))
    predicted = model.predict(test[FEATURES])
    probability = model.predict_proba(test[FEATURES])[:, list(model.classes_).index(1)]
    metrics = {
        "accuracy": round(float(accuracy_score(test[TARGET], predicted)), 4),
        "balanced_accuracy": round(float(balanced_accuracy_score(test[TARGET], predicted)), 4),
        "precision": round(float(precision_score(test[TARGET], predicted, zero_division=0)), 4),
        "recall": round(float(recall_score(test[TARGET], predicted, zero_division=0)), 4),
        "f1": round(float(f1_score(test[TARGET], predicted, zero_division=0)), 4),
        "roc_auc": round(float(roc_auc_score(test[TARGET], probability)), 4),
    }
    model_path, metadata_path = Path(args.model_out), Path(args.metadata_out)
    model_path.parent.mkdir(parents=True, exist_ok=True)
    metadata_path.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, model_path)
    metadata = {
        "model_type": "RandomForestClassifier",
        "model_version": "research-1",
        "target": TARGET,
        "features": FEATURES,
        "trained_at": datetime.now(timezone.utc).isoformat(),
        "source_file_name": source.name,
        "row_count": int(len(frame)),
        "train_rows": int(len(train)),
        "test_rows": int(len(test)),
        "train_period": [train["date"].min().isoformat(), train["date"].max().isoformat()],
        "test_period": [test["date"].min().isoformat(), test["date"].max().isoformat()],
        "evaluation": {"method": "chronological holdout; no random shuffle", "metrics": metrics},
        "scope": "research_only",
        "warning": "FIRMS hotspot proxy is not a verified fire label. Not validated for operational warnings or any region without local independent validation.",
    }
    metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    print(json.dumps({"model": str(model_path), "metadata": str(metadata_path), "evaluation": metadata["evaluation"]}, indent=2))


if __name__ == "__main__":
    main()
